### ISSUE TITLE
Cannot get sample Python nor web interface to work

### ISSUE THREAD

**Issue by philostow1** [grahamimac/corenlp-complete-docker#1]
Hi,
I've followed the steps to exercise the corenlp-complete-docker, but at http://127.0.0.1:9000/ i get:
```
Failed to load resource: net::ERR_TIMED_OUT
loading.gif:1 Failed to load resource: the server responded with a status of 404 (Not Found)
head.load.min.js:1 Failed to load resource: net::ERR_TIMED_OUT
corenlp-brat.js:9 Uncaught ReferenceError: head is not defined
    at corenlp-brat.js:9
```

I've also tried the python interface with similar results.
Suggestions and thanks.

**Comment by grahamimac** [comment]
Can you post the full docker and command line commands and their output. E.g., `docker run ...` and it's output, and also the results of `docker ps -a` listing active instances, and the Python you ran to test and it's output? Hard to debug from here without that info. I use this regularly and it seems to be working fine on my end.

Could be if you're building from the Dockerfile that the link is dead and out of date, as Stanford has upgraded to a new 4.0.0 build fairly recently and I haven't updated yet.

**Comment by philostow1** [comment]
```
PS C:\Users\320000256\PycharmProjects\StanfordCoreNLP> docker run -itd -p 9000:9000 --name corenlp graham3333/corenlp-complete
aa4c1f5a85885002e727ef96f7fb4efb33dc7bddaf4d3532b6a2f896a01221cd
PS C:\Users\320000256\PycharmProjects\StanfordCoreNLP> docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                    NAMES
aa4c1f5a8588        graham3333/corenlp-complete   "/bin/sh -c 'java -c…"   6 seconds ago       Up 5 seconds        0.0.0.0:9000->9000/tcp   corenlp
```
My python code is:

```
import json
import requests
        params = {'properties': '{"annotators": "tokenize,ssplit,lemma,pos,ner,depparse,openie,sentiment"}'}
        url = 'http://127.0.0.1:9000/'

        # Get information about the sentence from CoreNLP
        text = 'The quick brown fox jumped over the lazy dog.'
        r = requests.post(url, data=text, params=params, timeout=60)
        data = json.loads(r.text)
        print(json.dumps(data, sort_keys=True, indent=4, separators=(',', ': ')))
```

Python output:
```
(venv) C:\Users\320000256\PycharmProjects\StanfordCoreNLP>python main.py
Traceback (most recent call last):
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\320000256\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\320000256\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\320000256\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\320000256\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\320000256\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\320000256\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 25, in <module>
    r = requests.post(url, data=text, params=params, timeout=60)
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\320000256\PycharmProjects\StanfordCoreNLP\venv\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

(venv) C:\Users\320000256\PycharmProjects\StanfordCoreNLP>
```
Also, the process is killed after I attempt to run the python code above

```
PS C:\Users\320000256\PycharmProjects\StanfordCoreNLP> docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                    NAMES
8c1e5f833e8a        graham3333/corenlp-complete   "/bin/sh -c 'java -c…"   58 minutes ago      Up 58 minutes       0.0.0.0:9000->9000/tcp   corenlp
PS C:\Users\320000256\PycharmProjects\StanfordCoreNLP> docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                            PORTS               NAMES
8c1e5f833e8a        graham3333/corenlp-complete   "/bin/sh -c 'java -c…"   About an hour ago   Exited (137) About a minute ago                       corenlp
```

**Comment by philostow1** [comment]
I posted everything.

Phil Oxenberg

**Comment by grahamimac** [comment]
And you just ran `docker run ...` previously or `docker pull ...` to get it from DockerHub, correct? Or did you `docker build...` from the Dockerfile in this repo? If the latter I would remove the image and try pulling it from DockerHub. If the former, I would run while using Task Manager (if windows), Activity Monitor (if mac), or `top` or similar if Linux. My guess is your system is running out of memory. When you make the first call, CoreNLP initializes and loads the network into memory to start making predictions/analyze text and return results. Monitoring it as it starts up should help. 

I'd be interested in what you see when you do that, and whether that is CoreNLP or your system that is rejecting it and shutting it down. I typically run it on c5.xlarge or bigger on AWS when we use it here, with no other programs running, and that's 8 GB of dedicated RAM.  c5.2-4xlarge when using sentiment or other programs with bigger overhead on CoreNLP's models. I've run into trouble with 4 GB RAM or less fairly consistently (though not always), and generally check RAM first whenever I'm having an issue. I hope this helps.

**Comment by philostow1** [comment]
Hi Graham,
What I did this morning (Windows 10):
- Stopped apache tomcat
- Stopped Pycharm (these were the two biggest memory users)
- Memory usage now at 35% 
- In powershell:
1. docker rm corenlp
2. docker run -itd -p 9000:9000 --name corenlp graham3333/corenlp-complete
3. docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                    NAMES
b39a50ca02e7        graham3333/corenlp-complete   "/bin/sh -c 'java -c…"   34 seconds ago      Up 33 seconds       0.0.0.0:9000->9000/tcp   corenlp
- From Chrome: http://127.0.0.1:9000/ and then typed The quick brown fox jumped over the lazy dog,  Clicked Submit
- After a couple of minutes got this in the chrome debug console:
```
jquery-2.1.4.min.js:4 POST http://127.0.0.1:9000/?properties=%7B%22annotators%22%3A%20%22tokenize%2Cssplit%2Cpos%2Cner%2Cdepparse%2Copenie%22%2C%20%22date%22%3A%20%222020-07-13T06%3A53%3A18%22%7D&pipelineLanguage=en net::ERR_EMPTY_RESPONSE
send @ jquery-2.1.4.min.js:4
ajax @ jquery-2.1.4.min.js:4
(anonymous) @ corenlp-brat.js:987
dispatch @ jquery-2.1.4.min.js:3
r.handle @ jquery-2.1.4.min.js:3
```

- In powershell:
1. docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                        PORTS               NAMES
b39a50ca02e7        graham3333/corenlp-complete   "/bin/sh -c 'java -c…"   3 minutes ago       **Exited** (137) 14 seconds ago                       corenlp

**Comment by philostow1** [comment]
Hi Graham,
What I did this morning (Windows 10):

   - Stopped apache tomcat
   - Stopped Pycharm (these were the two biggest memory users)
   - Memory usage now at 35%  (My system has 32GB)
   - In powershell:


   1. docker rm corenlp
   2. docker run -itd -p 9000:9000 --name corenlp
   graham3333/corenlp-complete
   3. docker ps -a
   CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
   b39a50ca02e7 graham3333/corenlp-complete "/bin/sh -c 'java -c…" 34
   seconds ago Up 33 seconds 0.0.0.0:9000->9000/tcp corenlp


   - From Chrome: http://127.0.0.1:9000/ and then typed The quick brown fox
   jumped over the lazy dog, Clicked Submit
   - After a couple of minutes got this in the chrome debug console:

jquery-2.1.4.min.js:4 POST
http://127.0.0.1:9000/?properties=%7B%22annotators%22%3A%20%22tokenize%2Cssplit%2Cpos%2Cner%2Cdepparse%2Copenie%22%2C%20%22date%22%3A%20%222020-07-13T06%3A53%3A18%22%7D&pipelineLanguage=en
net::ERR_EMPTY_RESPONSE
send @ jquery-2.1.4.min.js:4
ajax @ jquery-2.1.4.min.js:4
(anonymous) @ corenlp-brat.js:987
dispatch @ jquery-2.1.4.min.js:3
r.handle @ jquery-2.1.4.min.js:3


   - In powershell:


   1. docker ps -a
   CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
   b39a50ca02e7 graham3333/corenlp-complete "/bin/sh -c 'java -c…" 3
   minutes ago Exited (137) 14 seconds ago corenlp


Thank you,
Phil

**Comment by grahamimac** [comment]
Interesting, Phil. You've now hit the limits of my experience with this. I've actually never attempted to run this on a windows machine using Docker before. I always use Linux. I would place a bet that there's something going on between the Ubuntu server using Windows resources to execute the task that is causing the error, though I can't for the life of me think of what it could be. 

I think I'd recommend reaching out to the CoreNLP folks at this point: https://github.com/stanfordnlp/CoreNLP or seeing if someone has resolved this with a better container. Or trying to build yourself using instructions here: https://stanfordnlp.github.io/CoreNLP/download.html. Sorry I couldn't be of more help!

**Comment by philostow1** [comment]
No worries I appreciated your help thus far.

I'm in the process of building it using the docker file you posted.

Thanks again and have a great day.

Phil

**Comment by philostow1** [comment]
Hi Graham,

I just noticed that the annotation types, named entities, conference, and
relations, crash the docker image.  The others appear to work!

Not sure why those crash, but progress.

Cheers,
Phil

**Comment by grahamimac** [comment]
Very frustrating, glad you were able to make progress though! I hope that continues to be the case.

**Comment by philostow1** [comment]
I also rebuilt it using the latest version 4.1.0. we'll see if that is any
better. Thanks again for the original post and never would have gotten this
far without it.
